export { PROTOCOL_VERSION, PACKAGE_VERSION } from "./version.js";
export { encodeBody, decodeBody } from "./body.js";
export { normalizeHeaders } from "./headers.js";
export {
  globToRegexPattern,
  resolveGlobToRegexPattern,
  urlMatches,
  matchSerializedMatcher,
  isURLPatternLike,
  type MatchInput,
  type URLMatch,
  type URLPatternLike,
} from "./match.js";
export { BackendMocksNetworkError, serializeError, errorFromCode } from "./errors.js";
export {
  parseJsonClientMessage,
  parseJsonProxyMessage,
  stringifyMessage,
} from "./parse-json.js";
export {
  backendErrorCodeSchema,
  serializedRequestSchema,
  serializedResponseSchema,
  serializedErrorSchema,
  serializedMatcherSchema,
  requestOverridesSchema,
  routeMatchDiagnosticSchema,
  historyEntrySchema,
  historyOutcomeSchema,
  historyActionSchema,
  historyEventSchema,
  wsConnectionOutcomeSchema,
  wsTimelineEventSchema,
  wsConnectionEntrySchema,
  connectionRoleSchema,
  clientToProxyMessageSchema,
  proxyToClientMessageSchema,
  parseClientToProxyMessage,
  parseProxyToClientMessage,
  type BackendErrorCode,
  type SerializedRequest,
  type SerializedResponse,
  type SerializedError,
  type SerializedMatcher,
  type RequestOverrides,
  type RouteMatchDiagnostic,
  type HistoryEntry,
  type HistoryAction,
  type HistoryEvent,
  type WsConnectionEntry,
  type WsConnectionOutcome,
  type WsTimelineEvent,
  type ConnectionRole,
  type ClientToProxyMessage,
  type ProxyToClientMessage,
  type RouteKind,
  type WsData,
  routeKindSchema,
  wsDataSchema,
} from "./schemas.js";
